model: resnet18
lr: 0.05
min_lr: 1e-6
epochs: 100
device: 'cuda'
batch_size: 64
log_interval: 500
output: output/cifar10/resnet18_resnet34_dist
num_classes: 10
pretrained: false
dataset_download: false
dataset: ciafr10

distiller: dist
teacher: resnet34
teacher_pretrained: false
teacher_weight: weights/resnet/cifar10_resnet34_84.23.pth.tar
kd_temperature: 4.0
kd_loss_weight: 1.0
gt_loss_weight: 1.0

dist_beta: 2.0
dist_gamma: 2.0