model: resnet50
lr: 5e-2
min_lr: 1e-4
epochs: 100
device: cuda
batch_size: 128
log_interval: 100
output: output/cifar100/resnet50_vanilla
num_classes: 100
pretrained: true
dataset: cifar100
dataset_download: false
weight: weights/resnet/resnet50_a1_0-14fe96d1.pth

distiller: vanilla
opt: sgd
weight_decay: 2e-3
sched: plateau
sched_gamma: 0.1
sched_patience: 10